### ISSUE TITLE
GPU rendering

### ISSUE THREAD

**Issue by fire** [sammycage/plutovg#11]
I was wondering using LunaSVG in Godot and have it create editable 2d shapes in Godot Editor via plutovg output.

Any thoughts?

**Comment by sammycage** [comment]
I will try to take a look at Godot Editor

**Comment by fire** [comment]
Here was a previous attempt.

https://github.com/godot-extended-libraries/godot_vector_graphics

**Comment by fire** [comment]
Here's the path to mesh code.

https://github.com/godot-extended-libraries/godot_vector_graphics/blob/master/tove2d/src/cpp/mesh/meshifier.cpp#L232

**Comment by sammycage** [comment]
I have to replace plutovg in [canvas.cpp](https://github.com/sammycage/lunasvg/blob/master/source/canvas.cpp) with the hardware accelerated renderer.

**Comment by sammycage** [comment]
Maybe I will try to add tove2d to lunasvg backends

**Comment by sammycage** [comment]
Now I get your points.. let's talk privately sammycageagle@gmail.com
