### ISSUE TITLE
Incorrect implementation of "plutovg_surface_write_to_png"

### ISSUE THREAD

**Issue by ZhUyU1997** [sammycage/plutovg#14]
```c
void plutovg_surface_write_to_png(const plutovg_surface_t* surface, const char* filename)
{
    ...
    unsigned char* image = malloc((size_t)(stride * height));
    ...
```
We should clear the memory of the "image". If not, the png may get unexpected pixels as below.
![output](https://user-images.githubusercontent.com/18410894/145690253-10f8d549-bf64-4743-9d3f-61730d8f9336.png)

**Comment by sammycage** [comment]
Thank you for reporting this issue
