### ISSUE TITLE
full fixed-point support

### ISSUE THREAD

**Issue by vvuk** [sammycage/plutovg#22]
I'd like to use plutovg on some systems without a FPU or with a very slow FPU -- e.g. ESP32 (S2/S3 with xtenesa instruction set or C3 with RISC-V).  I'm thinking of making this a compile-time option, by changing direct usage of `float`/`double` to plutovg-specific typedefs, and then using a library such as https://github.com/johnmcfarlane/cnl or https://github.com/MikeLankamp/fpm to optionally provide the implementation.  (Which would require the code to be compiled as C++ though.)

Is there any interest in such an option? I'll probably do the hack regardless, but if there's a chance to get it upstreamed I'll make an effort to make it cleaner :)

**Comment by sammycage** [comment]
> Is there any interest in such an option?

No

Sorry for my late reply

**Comment by THZthz** [comment]
You can use libfixmath if you want to work entirely on C.
