### ISSUE TITLE
stroke round_rect line width bug

### ISSUE THREAD

**Issue by goaq** [sammycage/plutovg#23]
When drawing round_rect, the line width cannot be set to 1px
```
    plutovg_save(pluto);
    plutovg_round_rect(pluto, 10, 10, 580, 50, 5, 5);
    plutovg_set_rgb(pluto, 0, 0, 1);
    plutovg_set_line_width(pluto, 1);
    plutovg_stroke_preserve(pluto);
    plutovg_stroke(pluto);
    plutovg_restore(pluto);
```
![some_shapes](https://user-images.githubusercontent.com/45125070/210329858-9d215168-4735-445d-8895-cece55c058f6.png)

**Comment by sammycage** [comment]
FreeType contour stroker is "buggy"... Maybe it's time to develop our own. Pull requests are welcome

https://github.com/sammycage/plutovg/blob/main/source/plutovg-ft-stroker.c
