### ISSUE TITLE
Use of longjmp()/setjmp()

### ISSUE THREAD

**Issue by ringtailsoftware** [sammycage/plutovg#27]
In the rasterizer, longjmp() and setjmp() are used.
https://github.com/sammycage/plutovg/blob/fa8002f43cf8ce0a233b582c8d54baaff944336d/source/plutovg-ft-raster.c#L293

I'm trying to port plutovg to a platform which doesn't support these. Is there a version of the rasterizer which doesn't need them?
I've tried bringing in an older version from freetype, but it seems to work differently - expecting a bitmap to render to rather than making callbacks.

**Comment by sammycage** [comment]
> Is there a version of the rasterizer which doesn't need them?

plutovg?? Noo

**Comment by sammycage** [comment]
Could you please share the older version from FreeType? Let me take a look and see how I can assist you.
