### ISSUE TITLE
Add support for bitmap rendering

### ISSUE THREAD

**Issue by ivantishchenko** [sammycage/plutovg#29]
Thank you for your work on plutovg.

Would it be possible to add support for rendering bitmaps?

**Comment by sammycage** [comment]
Could you provide more details about the specific requirements or use cases you have in mind for rendering bitmaps in plutovg?

**Comment by ivantishchenko** [comment]
Thank you for your reply @sammycage

The requirement is to load a PNG using stb image into an RGBA bitmap and then draw every pixel of this bitmap on a canvas along with other geometrical shapes. 

A use-case is to use PlutoVG in lunasvg to render a composition of geometrical vector shapes combined with raster images. Many SVGs use embedded raster images inside a <image> tag encoded in base64.

https://github.com/sammycage/lunasvg/issues/113

**Comment by sammycage** [comment]
🎉 Image rendering is now supported! 🖼️✨

https://github.com/sammycage/plutovg/blob/eee18c23a05126bd829d7a917e56386fa58b4657/include/plutovg.h#L190-L191
https://github.com/sammycage/plutovg/blob/eee18c23a05126bd829d7a917e56386fa58b4657/include/plutovg.h#L202-L206
