### ISSUE TITLE
Updates from 3rdparty/plutovg

### ISSUE THREAD

**Issue by ivantishchenko** [sammycage/plutovg#31]
It seems that there is a fork of this library inside lunasvg. Should the changes from the fork be applied here? This way this library can be used as a submodule in https://github.com/sammycage/lunasvg.

https://github.com/sammycage/lunasvg/tree/master/3rdparty/plutovg

**Comment by sammycage** [comment]
https://github.com/sammycage/lunasvg/issues/170
