### ISSUE TITLE
Feature Request: support for RGB565 surfaces (and possibly other formats)

### ISSUE THREAD

**Issue by massimilianogalanti** [sammycage/plutovg#33]
Hello,

I am experimenting with this library to implement a simple embedded graphic UI by creating a surface at the frame buffer address. Everything works fine as long as I set up the graphic controller to ARGB8888 and allocate RAM accordingly.

I am now thinking about saving some RAM by allocating a different pixel format frame buffer/surface (say RGB565, or ARGB4444...). Would it be possible to modify the code to support such change? Can you point me to the relevant functions?

Thank you for your work!

**Comment by sammycage** [comment]
> Would it be possible to modify the code to support such change?

Yes

> Can you point me to the relevant functions?

Please feel free to add your desired image format here: https://github.com/sammycage/plutovg/blob/main/source/plutovg-blend.c.
