### ISSUE TITLE
How to draw a image on surface?

### ISSUE THREAD

**Issue by tktkku** [sammycage/plutovg#37]
I want to draw a image, in a memory buffer, on the surface. With these lines I got a white area.
```C
// initial
plutovg_surface_t* surface = plutovg_surface_create(width, height);
plutovg_canvas_t* canvas = plutovg_canvas_create(surface);
plutovg_canvas_save(canvas);
plutovg_canvas_set_rgb(canvas, 1, 1, 1);
plutovg_canvas_paint(canvas);
plutovg_canvas_restore(canvas);

// draw lines and curves...

// try to draw image on surface
plutovg_surface_t* s = plutovg_surface_load_from_image_data(image->data, image->data_len);
plutovg_surface_write_to_jpg(s, filename, 100); // the image read correctly

plutovg_matrix_t m;
plutovg_matrix_init_identity(&m);
plutovg_canvas_set_texture(canvas, s, PLUTOVG_TEXTURE_TYPE_PLAIN, 0.5, &m);
plutovg_canvas_set_operator(canvas, PLUTOVG_OPERATOR_SRC);
plutovg_canvas_paint(canvas);
plutovg_surface_destroy(s);
// The area that was supposed to be an image is now blank
plutovg_surface_write_to_png(surface, "test.png"); 
```
There was a [similar issue](https://github.com/sammycage/plutovg/issues/25) before, but the API has changed so much that I'm not sure this is the right way to do it.
Can you give me some advice, please?

**Comment by sammycage** [comment]
Thank you for bringing this up! The API has indeed undergone significant changes, and to better assist you, it would be helpful to see the complete code you were using with the previous API. Could you please share the code so I can understand exactly what you're trying to achieve? If you'd prefer, you can also send it to me via email if you're unable to share it here. Looking forward to your response!

**Comment by tktkku** [comment]
Thank you for your reply.
After more testing, it shows that these actually work fine.  It's not about plutovg.  It was something else that was affecting the output. Sorry to bother you. I'll close this issue.

**Comment by tktkku** [comment]
Hi, sammycage:




Have you ever had experience with PDF rendering or are you interested in PDF rendering?We are developing a PDF renderer and this project is still in its infancy. We are using your project, the plutovg library,  as the rendering engine, but we are experiencing some problems and need assistance. 




When rendering some parts will not be rendered (e.g. tiger.pdf) or the image cannot be rendered to the surface. These problems may be related to parsing PDF errors, or they may be related to rendering. We had very little experience with rendering and were unable to understand how it worked when using this library.




We tried a lot and still can't figure out the problem, if you are interested, please check the attached file(project1.zip), which contains our parser's static library, and the file that calls plutovg for rendering, which you can compile using the Makefile inside. (But please note that all these source code or binaries are private, even if they don't use very advanced techniques; the documentation is also private, and since it contains personal privacy. Please don't distribute them, or I may be at legal risk.)




If you are willing to help us, our boss will pay you a small amount for your work, or a one-time sponsorship for the plutovg project. The exact amount is negotiable.




If you are not interested in this, please simply ignore the email. And sorry to bother you.

Thanks!

At 2024-08-29 11:21:09, "Samuel Ugochukwu" ***@***.***> wrote:

Thank you for bringing this up! The API has indeed undergone significant changes, and to better assist you, it would be helpful to see the complete code you were using with the previous API. Could you please share the code so I can understand exactly what you're trying to achieve? If you'd prefer, you can also send it to me via email if you're unable to share it here. Looking forward to your response!
