### ISSUE TITLE
Clarification needed on clipping

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [sammycage/plutovg#40]
Thanks for the great work. I've forked your offering to C++ and integrated it with my embedded graphics library after making some modifications to make it more suitable for low memory environments.

To that end, I need a way to position a canvas over a "surface" (a bitmap) where the bitmap is not overlaid over then entire canvas.

Basically, I'm in a situation where say, the top half of the canvas might have a backing surface/bitmap, but the bottom half does not (just as an example), for reasons that are complicated to explain in a brief matter, but critical.

What I'm hoping to do is to put a clipping rectangle in play that clips the entire canvas area to only the space where the backing bitmap is.

I'm almost certain this is possible after looking at your code. I just don't understand how to do it. The clip functions aren't entirely clear to me.

Thanks!

**Comment by codewitch-honey-crisis** [comment]
And of course soon after I post I find the magic sauce in your code. Sorry to bother you. I think I figured it out.

**Comment by sammycage** [comment]
Well done buddy, happy coding! 🎉

**Comment by codewitch-honey-crisis** [comment]
Hey, so I tried setting plutovg_canvas_clip_extents() and yet in plutovg-blend.c when I debug it, I'm getting spans with an x as small as 41 even though my clip x is 400.

What gives? Am I doing this wrong? How do I absolutely prevent spans from being generated outside of a particular clipping region?

**Comment by codewitch-honey-crisis** [comment]
Yeah looking at the code I can't work this out. Obviously plutovg_clip_extents() isn't the whole story.
I noticed the only place state->clipping gets set to true is when you call plutovg_canvas_clip() but i don't understand that function. It looks like plutovg_canvas_fill() or stroke() but that doesn't make sense to me. I'm trying to CLIP the fill and the stroke both. What do i do here?

**Comment by codewitch-honey-crisis** [comment]
Yeah, I've been trying since to use plutovg_canvas_clip_rect() but it's still not clipping.

I don't know how to use these clip functions. The code in plutovg_canvas_clip() makes them look like an alternative to plutovg_canvas_fill() or plutovg_canvas_stroke(), but that's not intuitive to me. I don't want to render the clip. I want to CLIP the fill and strokes i'm about to render.

Let me see if I can simplify this: I need an example of your smiley code, except i only want to see a 50,50 rectangle right out of the middle of the drawing. You should be able to do this by adding plutovg_canvas_clip() call(s) into that code somehow, right? So show me. Thanks!

**Comment by sammycage** [comment]
Hi,

`plutovg_canvas_clip()` works similarly to JavaScript canvas clip methods, especially Cairo. You can clip a specific region, and any drawing that follows is limited to the clipped area. Here’s an example that clips a 200x120 pixel region and then draws a red rectangle—only the part inside the clip will be visible:

**Without clip**:

```c
#include <plutovg.h>

int main(void)
{
    const int width = 300;
    const int height = 150;

    plutovg_surface_t* surface = plutovg_surface_create(width, height);
    plutovg_canvas_t* canvas = plutovg_canvas_create(surface);

    plutovg_canvas_set_rgb(canvas, 0, 0, 0);
    plutovg_canvas_stroke_rect(canvas, 50, 20, 200, 120);

    plutovg_canvas_set_rgb(canvas, 1, 0, 0);
    plutovg_canvas_fill_rect(canvas, 0, 0, 150, 100);

    plutovg_surface_write_to_png(surface, "without-clip.png");
    plutovg_canvas_destroy(canvas);
    plutovg_surface_destroy(surface);
    return 0;
}
```

![without-clip](https://github.com/user-attachments/assets/bfa062c6-f40b-4aa4-b5fb-15568b237c4f)


**With clip**:

```c
int main(void)
{
    const int width = 300;
    const int height = 150;

    plutovg_surface_t* surface = plutovg_surface_create(width, height);
    plutovg_canvas_t* canvas = plutovg_canvas_create(surface);

    plutovg_canvas_set_rgb(canvas, 0, 0, 0);
    plutovg_canvas_stroke_rect(canvas, 50, 20, 200, 120);

    plutovg_canvas_clip_rect(canvas, 50, 20, 200, 120);

    plutovg_canvas_set_rgb(canvas, 1, 0, 0);
    plutovg_canvas_fill_rect(canvas, 0, 0, 150, 100);

    plutovg_surface_write_to_png(surface, "with-clip.png");
    plutovg_canvas_destroy(canvas);
    plutovg_surface_destroy(surface);
    return 0;
}
```

![with-clip](https://github.com/user-attachments/assets/704350a7-1078-4b15-80cd-7fed4c7c5dca)


When you clip a region, future drawing is restricted to that clipped region. 

Functions like `plutovg_canvas_clip_rect()`, `plutovg_canvas_clip_path()`, and `plutovg_canvas_clip_text()` internally call `plutovg_canvas_clip()`. Here’s the implementation of `plutovg_canvas_clip_rect()`:

```c
void plutovg_canvas_clip_rect(plutovg_canvas_t* canvas, float x, float y, float w, float h)
{
    plutovg_canvas_new_path(canvas);
    plutovg_canvas_rect(canvas, x, y, w, h);
    plutovg_canvas_clip(canvas);
}
```

I hope this clarifies how to use it!

**Comment by codewitch-honey-crisis** [comment]
Perfect. Thanks so much for this. I come from a C and C++ background, and I haven't use Javascript much so that was totally off my radar. I appreciate you taking the time to help me sort this out.
