### ISSUE TITLE
crash on plutovg_canvas_add_text

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [sammycage/plutovg#42]
I'm getting a crash on the final line below. I am loading a valid OTF font which I have tested with STB's TTF engine many times over the years, after modifying it to stream. (My forked header is 95% compatible with the original, is tested as part of the LVGL test suite)
```cpp
plutovg_font_face_t* face = plutovg_font_face_load_from_stream(*info.ttf_font,(int)info.ttf_font_face,nullptr,nullptr);
if(face==nullptr) {
    return gfx_result::invalid_format; // TODO: might be out of memory
}
plutovg_canvas_set_font_face(CHND,face);
plutovg_canvas_add_text(CHND,info.text,info.text_byte_count,info.encoding,location.x,location.y);
```
Curiously, this function isn't getting past the `if(face->glyphs{msb][lsb])` which evaluates to true without ever running the code further down below the if:
```cpp
static glyph_t* get_glyph(const plutovg_font_face_t* face, plutovg_codepoint_t codepoint)
{
    unsigned int msb = (codepoint >> 8) & 0xFF;
    if(face->glyphs[msb] == NULL) {
        ((plutovg_font_face_t*)face)->glyphs[msb] = (glyph_t**)calloc(GLYPH_CACHE_SIZE, sizeof(glyph_t*));
    }

    unsigned int lsb = codepoint & 0xFF;
    if(face->glyphs[msb][lsb]) {
        return face->glyphs[msb][lsb];
    }

    glyph_t* glyph = (glyph_t*)malloc(sizeof(glyph_t));
    glyph->index = stbtt_FindGlyphIndex(&face->info, codepoint);
    glyph->nvertices = stbtt_GetGlyphShape(&face->info, glyph->index, &glyph->vertices);
    stbtt_GetGlyphHMetrics(&face->info, glyph->index, &glyph->advance_width, &glyph->left_side_bearing);
    if(!stbtt_GetGlyphBox(&face->info, glyph->index, &glyph->x1, &glyph->y1, &glyph->x2, &glyph->y2))
        glyph->x1 = glyph->y1 = glyph->x2 = glyph->y2 = 0.f;
    return (face->glyphs[msb][lsb] = glyph);
}
```

Am I doing something wrong?

**Comment by sammycage** [comment]
The code itself looks fine, and I don't see anything immediately wrong with it. It's possible that the issue might be happening elsewhere, potentially causing a segmentation fault or another problem before the function is called. I would recommend using a debugger to step through and identify if there's a memory-related issue or if something unexpected is happening just before this section of the code.

**Comment by codewitch-honey-crisis** [comment]
I am in a debugger, and it looks the glyph is never getting initialized. That code after the if NEVER runs, as I said. And face-glyphs[msb][lsb] seems to hold a null but it's hard to tell since it's multi-dimmed and i forget how C/C++ lay those out in memory:
This is what I'm seeing

![Screenshot 2024-10-11 080847](https://github.com/user-attachments/assets/8337d300-7e10-486d-bf74-1e5960b43fdf)

When I get into get_glyph() things get suspicious: It calloc's so obv it's the first iteration

![Screenshot 2024-10-11 081044](https://github.com/user-attachments/assets/7060a027-3d18-4111-8b15-69012033d9ba)

But then it goes here. Always here. 

![Screenshot 2024-10-11 081109](https://github.com/user-attachments/assets/948580bc-de72-4ea0-b339-8054b99597ac)

Here's some debug at the point in the last screen grab:
![Screenshot 2024-10-11 081158](https://github.com/user-attachments/assets/1428d71a-8212-488d-8257-152b5bd6ac02)

![Screenshot 2024-10-11 081258](https://github.com/user-attachments/assets/62ef04b8-b1c1-492d-be43-a4f3c21a362b)

It almost feels like it's walking off the edge, like the calloc wasn't big enough. Any ideas?

**Comment by sammycage** [comment]
Thanks for sharing all the details! It looks like the issue might be with the size of the cache. For this function to work correctly, **GLYPH_CACHE_SIZE must be 256**. Could you check if that's the case in your code? Let me know if this helps!

**Comment by codewitch-honey-crisis** [comment]
It's 16. I may have lowered it. It could be a problem on embedded systems.
________________________________

**Comment by sammycage** [comment]
If you change it to 16, that means the algorithm in the `get_glyph` function will need to be adjusted accordingly. You might want to consider using a map to handle the glyph caching more dynamically in this case.

**Comment by codewitch-honey-crisis** [comment]
Well I changed that to 256, and now the issue is it's looping forever traversing the glyph paths. It could be a bug in my STB code if you're using functions I haven't exercised but I don't know enough about your glyph traversal function to figure out why it's hanging. Like, where.

I just checked in the hanging version
